# Generated by Django 5.0.1 on 2025-02-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='categorias.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='marcas.marca')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
