# Generated by Django 5.0.1 on 2025-02-16 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='produtos.produto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
