# Generated by Django 5.0.1 on 2025-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_created_at_cliente_operador_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
