# Generated by Django 5.0.1 on 2025-02-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
